### ISSUE TITLE
Version compatibility query

### ISSUE THREAD

**Issue by boardtc** [bartoszadamczyk/glowing-darcula#1]
I have a fall back license for ultimate 2019.3.x. Is the settings that much different that it's not compatible?

**Comment by bartoszadamczyk** [comment]
The only reason is that I have published the plugin at the beginning of 2021, and I had no time to test older versions. Testing all the flavours of the JetBrains apps was time-consuming enough.

I can pull 2019.03 and test it for you. If possible you should be able to download it from the marketplace in the next few days.

**Comment by bartoszadamczyk** [comment]
I've tested and extended the compatibility list of the theme. New version has been approved by JetBrains team and is now available in the [marketplace](https://plugins.jetbrains.com/plugin/15905-glowing-darcula).

Cheers!
